/* ─────────────────────────────────────────────────────────────────────────
   SERVI catalog — compact, English-canonical mirror of browse-data.js.
   Used to GROUND the AI parse (so matches map to real services) and to power
   the heuristic fallback when no LLM is available.
   Shape per category: { emoji, label, subs: [{ key, label, services:[], kw:[] }] }
   ──────────────────────────────────────────────────────────────────────── */
window.SERVI_CATALOG = {
  cleaning: {
    emoji: '🧹', label: 'Cleaning',
    subs: [
      { key: 'home-cleaning', label: 'Home cleaning',
        services: ['Weekly apartment cleaning', 'Kitchen and stove cleaning', 'Full bathroom cleaning', 'Dusting and vacuuming bedrooms and living room', 'Pre-guest home refresh'],
        kw: ['clean', 'cleaning', 'apartment', 'kitchen', 'bathroom', 'vacuum', 'dust', 'tidy', 'house', 'home', 'maid'] },
      { key: 'deep-cleaning', label: 'Deep cleaning',
        services: ['Post-party deep cleaning', 'Oven and refrigerator interior cleaning', 'Bathroom grout and scale removal', 'Closet and pantry deep clean', 'Seasonal whole-home deep cleaning'],
        kw: ['deep', 'scrub', 'oven', 'fridge', 'refrigerator', 'grout', 'scale', 'mold', 'pantry', 'messy', 'move out', 'moveout'] },
      { key: 'dry-cleaning', label: 'Dry cleaning',
        services: ['Dry cleaning for suits and blazers', 'Dress stain removal', 'Blanket and comforter cleaning', 'Curtain and linen cleaning', 'Weekday garment pickup and delivery'],
        kw: ['dry clean', 'laundry', 'suit', 'blazer', 'dress', 'stain', 'blanket', 'comforter', 'curtain', 'garment', 'iron'] },
    ],
  },
  repair: {
    emoji: '🔧', label: 'Repair & Maintenance',
    subs: [
      { key: 'gardening', label: 'Gardening',
        services: ['Lawn mowing', 'General garden maintenance', 'Shrub and hedge trimming', 'Irrigation system check', 'Leaf removal and outdoor cleanup'],
        kw: ['lawn', 'mow', 'garden', 'hedge', 'shrub', 'grass', 'irrigation', 'sprinkler', 'leaves', 'yard', 'plants'] },
      { key: 'plumbing', label: 'Plumbing',
        services: ['Sink or drain unclogging', 'Toilet leak repair', 'Faucet or mixer replacement', 'Water heater diagnosis', 'Pipe leak repair', 'Low water pressure repair'],
        kw: ['plumb', 'plumber', 'sink', 'drain', 'clog', 'clogged', 'toilet', 'leak', 'leaking', 'faucet', 'tap', 'pipe', 'water', 'heater', 'boiler', 'flood', 'flooding', 'pressure'] },
      { key: 'electrical', label: 'Electrical',
        services: ['Light fixture installation', 'Outlet and switch replacement', 'Short circuit or breaker troubleshooting', 'Ceiling fan installation', 'Interior wiring inspection'],
        kw: ['electric', 'electrical', 'electrician', 'light', 'lamp', 'fixture', 'outlet', 'socket', 'switch', 'breaker', 'short', 'circuit', 'fan', 'wiring', 'power', 'spark'] },
      { key: 'carpentry', label: 'Carpentry',
        services: ['Custom shelf installation', 'Closet or cabinet door repair', 'Interior door alignment', 'Wood furniture repair', 'Baseboard and trim installation'],
        kw: ['carpenter', 'carpentry', 'wood', 'shelf', 'shelves', 'cabinet', 'closet', 'door', 'furniture', 'baseboard', 'trim', 'molding'] },
      { key: 'locksmith', label: 'Locksmith',
        services: ['Emergency home lockout', 'Car lockouts', 'Key duplication', 'Smart lock installation', 'Stuck lock adjustment'],
        kw: ['lock', 'locksmith', 'lockout', 'locked out', 'key', 'keys', 'smart lock', 'deadbolt'] },
      { key: 'handyman', label: 'Handyman',
        services: ['TV wall mounting', 'Small wall patching and repairs', 'Curtain rod or blind installation', 'Kitchen or bathroom caulking', 'Hanging mirrors, frames, or accessories'],
        kw: ['handyman', 'mount', 'tv', 'wall', 'patch', 'hole', 'curtain rod', 'blind', 'caulk', 'silicone', 'hang', 'mirror', 'frame', 'fix', 'odd job'] },
      { key: 'assembly-installation', label: 'Assembly & installation',
        services: ['Bed frame assembly', 'Desk or bookcase assembly', 'Modular shelving installation', 'Washer or dryer hookup', 'Flat-pack furniture installation'],
        kw: ['assembly', 'assemble', 'install', 'bed frame', 'desk', 'bookcase', 'shelving', 'washer', 'dryer', 'ikea', 'flat pack', 'flatpack', 'furniture'] },
      { key: 'tailoring', label: 'Tailoring',
        services: ['Pant hemming', 'Dress or skirt alterations', 'Zipper replacement', 'Blazer or suit tailoring', 'Curtain or tablecloth alterations'],
        kw: ['tailor', 'sew', 'sewing', 'hem', 'alteration', 'zipper', 'stitch', 'seamstress'] },
    ],
  },
  moving: {
    emoji: '📦', label: 'Move & Transport',
    subs: [
      { key: 'moving', label: 'Moving',
        services: ['In-city apartment move', 'Packing help for moving boxes', 'Truck loading and unloading', 'Move-in setup assistance'],
        kw: ['move', 'moving', 'mover', 'movers', 'relocate', 'packing', 'boxes', 'truck', 'load', 'unload', 'apartment move'] },
      { key: 'large-items', label: 'Large items',
        services: ['Sofa transport', 'Mattress and bed base moving', 'Refrigerator or washer relocation', 'Large dining table delivery'],
        kw: ['sofa', 'couch', 'mattress', 'bed', 'fridge', 'refrigerator', 'washer', 'dining table', 'heavy', 'large item', 'furniture move'] },
      { key: 'errands', label: 'Errands',
        services: ['Urgent grocery run', 'Pharmacy pickup', 'Document or key drop-off', 'Store returns and exchanges'],
        kw: ['errand', 'grocery', 'groceries', 'pharmacy', 'pickup', 'drop off', 'dropoff', 'return', 'exchange', 'pick up'] },
      { key: 'deliveries', label: 'Deliveries',
        services: ['Same-day express delivery', 'Large store purchase delivery', 'Catering tray delivery', 'Flower or gift delivery', 'Scheduled recurring delivery route'],
        kw: ['delivery', 'deliver', 'courier', 'send', 'parcel', 'package', 'flowers', 'gift', 'same day'] },
    ],
  },
  wellness: {
    emoji: '💆', label: 'Wellness & Personal Care',
    subs: [
      { key: 'massage', label: 'Massage',
        services: ['In-home relaxation massage', 'Deep-tension back massage', 'Couples massage session', 'Muscle recovery massage', 'Post-travel or stress relief massage'],
        kw: ['massage', 'masseuse', 'relax', 'back massage', 'tension', 'spa', 'muscle', 'knots'] },
      { key: 'therapist', label: 'Therapist',
        services: ['Online individual therapy session', 'Stress and anxiety counseling', 'Couples therapy', 'Grief or life-transition support', 'Introductory teen counseling session'],
        kw: ['therapy', 'therapist', 'counseling', 'counselor', 'anxiety', 'stress', 'psychologist', 'mental'] },
      { key: 'personal-trainer', label: 'Personal trainer',
        services: ['At-home strength workout', 'Weight-loss plan kickoff', 'Mobility and stretching session', 'Beginner fitness training', 'Low-impact conditioning workout'],
        kw: ['trainer', 'personal trainer', 'workout', 'fitness', 'gym', 'exercise', 'strength', 'stretch', 'weight loss'] },
      { key: 'pet-care', label: 'Pet care',
        services: ['Daily dog walking', 'Pet sitting during travel', 'Basic bath and brushing', 'Feeding and water refill visit', 'Medication support visit'],
        kw: ['pet', 'dog', 'cat', 'walk', 'walking', 'pet sitting', 'petsitting', 'groom', 'bath', 'feed', 'puppy'] },
      { key: 'child-care', label: 'Child care',
        services: ['After-school babysitting', 'Evening babysitter for date night', 'School pickup and in-home care', 'Weekend nanny support', 'Hourly infant care'],
        kw: ['babysit', 'babysitter', 'nanny', 'child', 'kids', 'childcare', 'baby', 'infant', 'sitter'] },
      { key: 'elder-assistance', label: 'Elder assistance',
        services: ['Companion visit at home', 'Medication reminder support', 'Medical appointment accompaniment', 'Light meal-prep assistance', 'Walking and basic mobility support'],
        kw: ['elder', 'elderly', 'senior', 'companion', 'caregiver', 'grandparent', 'mobility', 'medication'] },
    ],
  },
  suppliers: {
    emoji: '🛒', label: 'Suppliers',
    subs: [
      { key: 'artisan-bread', label: 'Artisan bread',
        services: ['Sourdough bread order', 'Brioche and pastry box', 'Brunch or breakfast bakery order', 'Dinner rolls and buns order', 'Weekly bread subscription'],
        kw: ['bread', 'sourdough', 'bakery', 'pastry', 'brioche', 'rolls', 'baked'] },
      { key: 'fresh-dairy', label: 'Fresh dairy',
        services: ['Milk and yogurt restock', 'Artisan cheese board order', 'Butter and cream delivery', 'Lactose-free dairy delivery', 'Breakfast dairy bundle'],
        kw: ['dairy', 'milk', 'yogurt', 'cheese', 'butter', 'cream'] },
      { key: 'pharmacy', label: 'Pharmacy',
        services: ['Same-day prescription pickup', 'Over-the-counter medication order', 'First-aid kit refill', 'Baby care essentials order'],
        kw: ['pharmacy', 'prescription', 'medicine', 'medication', 'drugstore', 'first aid'] },
      { key: 'catering', label: 'Catering',
        services: ['Office lunch trays', 'Brunch catering setup', 'Cocktail bites for events', 'Family buffet catering', 'Boxed lunches for small teams'],
        kw: ['catering', 'cater', 'lunch tray', 'buffet', 'event food', 'canapes', 'office lunch', 'party food'] },
      { key: 'organic-butcher', label: 'Organic butcher',
        services: ['Steak and grill order', 'Weekly chicken pack', 'Ground meat for burgers', 'Specialty cuts by request', 'Soup bones and broth staples'],
        kw: ['butcher', 'meat', 'steak', 'beef', 'chicken', 'pork', 'cuts', 'grill'] },
      { key: 'fish', label: 'Fish',
        services: ['Salmon fillet delivery', 'Fresh shrimp order', 'Sushi-grade tuna order', 'Family seafood pack', 'Whole fish cleaned and ready to cook'],
        kw: ['fish', 'seafood', 'salmon', 'shrimp', 'tuna', 'sushi', 'fishmonger'] },
      { key: 'organic-vegetables', label: 'Organic vegetables',
        services: ['Weekly organic produce box', 'Leafy greens and salad restock', 'Seasonal cooking vegetables', 'Juicing and smoothie bundle', 'Family fruit and vegetable basket'],
        kw: ['vegetable', 'veggies', 'produce', 'organic', 'greens', 'salad', 'fruit', 'grocery box'] },
    ],
  },
};

/* Canned follow-up questions per subcategory — used by the heuristic engine
   (and as a safety net for the AI engine). Each: { q, key, chips? } */
window.SERVI_FOLLOWUPS = {
  'home-cleaning':   [{ q: 'How big is the space?', key: 'size', chips: ['Studio', '1–2 bedrooms', '3+ bedrooms'] }, { q: 'Which areas need the most attention?', key: 'areas', chips: ['Kitchen', 'Bathrooms', 'Whole place'] }],
  'deep-cleaning':   [{ q: 'What triggered the deep clean?', key: 'reason', chips: ['Move in / out', 'After an event', 'Seasonal reset'] }, { q: 'Roughly how many bedrooms?', key: 'size', chips: ['1', '2', '3+'] }],
  'dry-cleaning':    [{ q: 'What needs cleaning?', key: 'items', chips: ['Suits', 'Dresses', 'Bedding'] }, { q: 'Need pickup & delivery?', key: 'pickup', chips: ['Yes', 'I’ll drop off'] }],
  'plumbing':        [{ q: 'Which fixture is affected?', key: 'fixture', chips: ['Sink', 'Toilet', 'Shower', 'Pipes'] }, { q: 'Is water leaking right now?', key: 'severity', chips: ['Yes, actively', 'A little', 'No'] }],
  'electrical':      [{ q: 'What’s the issue?', key: 'issue', chips: ['No power', 'Install fixture', 'Outlet / switch', 'Breaker tripping'] }, { q: 'How many points are affected?', key: 'count', chips: ['One', 'A few', 'Whole home'] }],
  'carpentry':       [{ q: 'What needs work?', key: 'object', chips: ['Door', 'Shelf / cabinet', 'Furniture'] }],
  'locksmith':       [{ q: 'What do you need?', key: 'need', chips: ['Locked out now', 'New lock', 'Key copy'] }, { q: 'Is this urgent?', key: 'urgent', chips: ['Yes, I’m stuck', 'No rush'] }],
  'handyman':        [{ q: 'What’s the task?', key: 'task', chips: ['Mount / hang something', 'Patch a wall', 'Install a fixture', 'Other'] }],
  'assembly-installation': [{ q: 'What are we assembling?', key: 'item', chips: ['Bed', 'Desk / shelf', 'Appliance', 'Other'] }],
  'tailoring':       [{ q: 'What kind of work?', key: 'work', chips: ['Hemming', 'Alterations', 'Zipper / repair'] }],
  'moving':          [{ q: 'How big is the move?', key: 'size', chips: ['A few items', 'Studio / 1BR', '2BR+'] }, { q: 'Do you need packing help?', key: 'packing', chips: ['Yes', 'Just moving'] }],
  'large-items':     [{ q: 'What’s being moved?', key: 'item', chips: ['Sofa', 'Mattress', 'Appliance', 'Other'] }, { q: 'Any stairs or elevator?', key: 'access', chips: ['Elevator', 'Stairs', 'Ground floor'] }],
  'errands':         [{ q: 'What’s the errand?', key: 'errand', chips: ['Groceries', 'Pharmacy', 'Pickup / drop-off'] }],
  'deliveries':      [{ q: 'What are we delivering?', key: 'item', chips: ['A package', 'Food / catering', 'Flowers / gift'] }],
  'massage':         [{ q: 'What type of massage?', key: 'type', chips: ['Relaxation', 'Deep tension', 'Recovery'] }, { q: 'For how many people?', key: 'people', chips: ['Just me', 'Two'] }],
  'therapist':       [{ q: 'What kind of support?', key: 'type', chips: ['Individual', 'Couples', 'Teen'] }],
  'personal-trainer':[{ q: 'What’s your goal?', key: 'goal', chips: ['Strength', 'Weight loss', 'Mobility'] }],
  'pet-care':        [{ q: 'What does your pet need?', key: 'need', chips: ['Walking', 'Sitting', 'Grooming'] }, { q: 'What kind of pet?', key: 'pet', chips: ['Dog', 'Cat', 'Other'] }],
  'child-care':      [{ q: 'When do you need care?', key: 'when', chips: ['After school', 'Evening', 'Weekend'] }, { q: 'Ages of the kids?', key: 'ages', chips: ['Infant', 'Toddler', 'School-age'] }],
  'elder-assistance':[{ q: 'What kind of help?', key: 'help', chips: ['Companionship', 'Appointments', 'Daily tasks'] }],
  'catering':        [{ q: 'What’s the occasion?', key: 'occasion', chips: ['Office', 'Party', 'Small group'] }, { q: 'Roughly how many people?', key: 'guests', chips: ['<10', '10–25', '25+'] }],
  'pharmacy':        [{ q: 'What do you need?', key: 'need', chips: ['Prescription', 'Over-the-counter', 'Baby care'] }],
};

/* Generic fallback when nothing matches / off-catalog request. */
window.SERVI_GENERIC_FOLLOWUPS = [
  { q: 'Roughly when do you need it?', key: 'timing', chips: ['As soon as possible', 'This week', 'Flexible'] },
  { q: 'Anything we should know up front?', key: 'notes' },
];
