/* ─────────────────────────────────────────────────────────────────────────
   SERVI — tailored "tell us more" follow-up questions per subcategory.
   Loaded by service.html. Bilingual (ES/EN), shown as optional tap-to-answer
   chips (and a few short open-text questions) in the booking sidebar so the
   admin gets quick dispatch context without interrogating the customer.

   Shape per subcategory key (matches browse-data.js / smart-request catalog):
     [{ key, type:'chips'|'text', q:{es,en}, label:{es,en}, chips:[{es,en}] }]
   - key:    short lowercase id, unique within the subcategory.
   - q:      the full question shown to the customer.
   - label:  1-2 word noun used as a prefix in the order summary (label: answer).
   - type:   'chips' → tap one option (chips populated); 'text' → short open answer (chips: []).
   These are intentionally NOT too specific — no measurements, brands, or prices.
   ──────────────────────────────────────────────────────────────────────── */
window.SERVI_SERVICE_DETAILS = {
  // ── Cleaning ──────────────────────────────────────────────────────────────
  'home-cleaning': [
    { key: 'scope', type: 'chips',
      q: { es: '¿Qué quieres que limpiemos?', en: 'What do you want us to clean?' },
      label: { es: 'Alcance', en: 'Scope' },
      chips: [
        { es: 'Toda la casa', en: 'Whole home' },
        { es: 'Cocina', en: 'Kitchen' },
        { es: 'Baños', en: 'Bathrooms' },
        { es: 'Recámaras', en: 'Bedrooms' },
      ] },
    { key: 'size', type: 'chips',
      q: { es: '¿Qué tan grande es el lugar?', en: 'How big is the place?' },
      label: { es: 'Tamaño', en: 'Size' },
      chips: [
        { es: '1-2 recámaras', en: '1-2 bedrooms' },
        { es: '3-4 recámaras', en: '3-4 bedrooms' },
        { es: 'Más de 4', en: 'More than 4' },
      ] },
    { key: 'recurrence', type: 'chips',
      q: { es: '¿Cada cuándo lo necesitas?', en: 'How often do you need it?' },
      label: { es: 'Frecuencia', en: 'Frequency' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Semanal', en: 'Weekly' },
        { es: 'Quincenal', en: 'Biweekly' },
      ] },
  ],
  'deep-cleaning': [
    { key: 'focus', type: 'chips',
      q: { es: '¿En qué nos enfocamos?', en: 'What should we focus on?' },
      label: { es: 'Enfoque', en: 'Focus' },
      chips: [
        { es: 'Toda la casa', en: 'Whole home' },
        { es: 'Cocina', en: 'Kitchen' },
        { es: 'Baños', en: 'Bathrooms' },
        { es: 'Clósets', en: 'Closets' },
      ] },
    { key: 'condition', type: 'chips',
      q: { es: '¿Cómo está el lugar ahorita?', en: "What's the current condition?" },
      label: { es: 'Estado', en: 'Condition' },
      chips: [
        { es: 'Solo mantenimiento', en: 'Just upkeep' },
        { es: 'Necesita atención', en: 'Needs attention' },
        { es: 'Muy descuidado', en: 'Very neglected' },
      ] },
  ],
  'dry-cleaning': [
    { key: 'type', type: 'chips',
      q: { es: '¿Qué tipo de prendas son?', en: 'What kind of items are they?' },
      label: { es: 'Prendas', en: 'Items' },
      chips: [
        { es: 'Trajes y sacos', en: 'Suits & blazers' },
        { es: 'Vestidos', en: 'Dresses' },
        { es: 'Edredones y cobijas', en: 'Comforters & blankets' },
        { es: 'Cortinas y blancos', en: 'Curtains & linens' },
      ] },
    { key: 'count', type: 'chips',
      q: { es: '¿Más o menos cuántas piezas?', en: 'Roughly how many pieces?' },
      label: { es: 'Cantidad', en: 'Count' },
      chips: [
        { es: '1-3 piezas', en: '1-3 pieces' },
        { es: '4-8 piezas', en: '4-8 pieces' },
        { es: 'Más de 8', en: 'More than 8' },
      ] },
    { key: 'pickup', type: 'chips',
      q: { es: '¿Necesitas que las recojamos y entreguemos?', en: 'Do you need pickup and delivery?' },
      label: { es: 'Recolección', en: 'Pickup' },
      chips: [
        { es: 'Sí, en mi casa', en: 'Yes, at home' },
        { es: 'Yo las llevo', en: "I'll drop off" },
      ] },
  ],

  // ── Repair & Maintenance ──────────────────────────────────────────────────
  'gardening': [
    { key: 'task', type: 'chips',
      q: { es: '¿Qué necesitas en el jardín?', en: 'What does your garden need?' },
      label: { es: 'Tarea', en: 'Task' },
      chips: [
        { es: 'Cortar pasto', en: 'Mow lawn' },
        { es: 'Podar', en: 'Trim & prune' },
        { es: 'Mantenimiento general', en: 'General upkeep' },
        { es: 'Limpieza de hojas', en: 'Leaf cleanup' },
      ] },
    { key: 'size', type: 'chips',
      q: { es: '¿Qué tan grande es el área?', en: 'How big is the area?' },
      label: { es: 'Tamaño', en: 'Size' },
      chips: [
        { es: 'Jardín chico', en: 'Small yard' },
        { es: 'Mediano', en: 'Medium' },
        { es: 'Grande', en: 'Large' },
      ] },
    { key: 'recurrence', type: 'chips',
      q: { es: '¿Cada cuándo lo necesitas?', en: 'How often do you need it?' },
      label: { es: 'Frecuencia', en: 'Frequency' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Mensual', en: 'Monthly' },
        { es: 'Cada semana', en: 'Weekly' },
      ] },
  ],
  'plumbing': [
    { key: 'fixture', type: 'chips',
      q: { es: '¿Qué punto tiene el problema?', en: 'Which fixture has the issue?' },
      label: { es: 'Punto', en: 'Fixture' },
      chips: [
        { es: 'Lavabo o fregadero', en: 'Sink or drain' },
        { es: 'WC', en: 'Toilet' },
        { es: 'Regadera', en: 'Shower' },
        { es: 'Tubería', en: 'Pipes' },
        { es: 'Boiler', en: 'Water heater' },
      ] },
    { key: 'severity', type: 'chips',
      q: { es: '¿Está fugando agua en este momento?', en: 'Is water leaking right now?' },
      label: { es: 'Fuga', en: 'Leak' },
      chips: [
        { es: 'Sí, está fugando', en: 'Yes, leaking now' },
        { es: 'Solo gotea', en: 'Just dripping' },
        { es: 'No hay fuga', en: 'No leak' },
      ] },
    { key: 'urgency', type: 'chips',
      q: { es: '¿Qué tan urgente es?', en: 'How urgent is it?' },
      label: { es: 'Urgencia', en: 'Urgency' },
      chips: [
        { es: 'Urgente', en: 'Urgent' },
        { es: 'Esta semana', en: 'This week' },
        { es: 'Sin prisa', en: 'No rush' },
      ] },
  ],
  'electrical': [
    { key: 'issue', type: 'chips',
      q: { es: '¿Cuál es el problema?', en: "What's the issue?" },
      label: { es: 'Problema', en: 'Issue' },
      chips: [
        { es: 'Sin luz', en: 'No power' },
        { es: 'Instalar algo', en: 'Install a fixture' },
        { es: 'Contacto o apagador', en: 'Outlet or switch' },
        { es: 'Breaker se bota', en: 'Breaker tripping' },
      ] },
    { key: 'scope', type: 'chips',
      q: { es: '¿Cuántos puntos están afectados?', en: 'How many spots are affected?' },
      label: { es: 'Alcance', en: 'Scope' },
      chips: [
        { es: 'Un punto', en: 'One spot' },
        { es: 'Varios', en: 'A few' },
        { es: 'Toda la casa', en: 'Whole home' },
      ] },
  ],
  'carpentry': [
    { key: 'object', type: 'chips',
      q: { es: '¿Qué necesita trabajo?', en: 'What needs work?' },
      label: { es: 'Objeto', en: 'Object' },
      chips: [
        { es: 'Puerta', en: 'Door' },
        { es: 'Repisa o gabinete', en: 'Shelf or cabinet' },
        { es: 'Mueble', en: 'Furniture' },
        { es: 'Zoclos o molduras', en: 'Baseboards or trim' },
      ] },
    { key: 'work', type: 'chips',
      q: { es: '¿Qué tipo de trabajo es?', en: 'What kind of work is it?' },
      label: { es: 'Trabajo', en: 'Work' },
      chips: [
        { es: 'Reparar', en: 'Repair' },
        { es: 'Instalar', en: 'Install' },
        { es: 'Ajustar', en: 'Adjust' },
      ] },
  ],
  'locksmith': [
    { key: 'need', type: 'chips',
      q: { es: '¿Qué necesitas?', en: 'What do you need?' },
      label: { es: 'Necesito', en: 'Need' },
      chips: [
        { es: 'Estoy encerrado', en: 'Locked out now' },
        { es: 'Cambiar cerradura', en: 'New lock' },
        { es: 'Copia de llave', en: 'Key copy' },
        { es: 'Cerradura atorada', en: 'Stuck lock' },
      ] },
    { key: 'urgency', type: 'chips',
      q: { es: '¿Es urgente?', en: 'Is it urgent?' },
      label: { es: 'Urgencia', en: 'Urgency' },
      chips: [
        { es: 'Urgente, estoy varado', en: "Urgent, I'm stuck" },
        { es: 'Hoy', en: 'Today' },
        { es: 'Sin prisa', en: 'No rush' },
      ] },
  ],
  'handyman': [
    { key: 'task', type: 'chips',
      q: { es: '¿Cuál es la tarea?', en: "What's the task?" },
      label: { es: 'Tarea', en: 'Task' },
      chips: [
        { es: 'Colgar o montar', en: 'Hang or mount' },
        { es: 'Resanar pared', en: 'Patch a wall' },
        { es: 'Instalar accesorio', en: 'Install a fixture' },
        { es: 'Sellar con silicón', en: 'Caulk & seal' },
      ] },
    { key: 'count', type: 'chips',
      q: { es: '¿Cuántas tareas son?', en: 'How many tasks are there?' },
      label: { es: 'Tareas', en: 'Tasks' },
      chips: [
        { es: 'Una cosa', en: 'One thing' },
        { es: 'Algunas', en: 'A few' },
        { es: 'Varias', en: 'Several' },
      ] },
  ],
  'assembly-installation': [
    { key: 'item', type: 'chips',
      q: { es: '¿Qué vamos a armar?', en: 'What are we assembling?' },
      label: { es: 'Mueble', en: 'Item' },
      chips: [
        { es: 'Cama', en: 'Bed' },
        { es: 'Escritorio o librero', en: 'Desk or bookcase' },
        { es: 'Estantería', en: 'Shelving' },
        { es: 'Electrodoméstico', en: 'Appliance' },
        { es: 'Otro', en: 'Other' },
      ] },
    { key: 'count', type: 'chips',
      q: { es: '¿Cuántas piezas son?', en: 'How many items?' },
      label: { es: 'Piezas', en: 'Items' },
      chips: [
        { es: 'Una', en: 'One' },
        { es: '2-3', en: '2-3' },
        { es: 'Más de 3', en: 'More than 3' },
      ] },
  ],
  'tailoring': [
    { key: 'work', type: 'chips',
      q: { es: '¿Qué tipo de arreglo necesitas?', en: 'What kind of work do you need?' },
      label: { es: 'Trabajo', en: 'Work' },
      chips: [
        { es: 'Dobladillo', en: 'Hemming' },
        { es: 'Ajuste', en: 'Alterations' },
        { es: 'Cierre o reparación', en: 'Zipper or repair' },
      ] },
    { key: 'garment', type: 'chips',
      q: { es: '¿Qué prenda es?', en: 'Which garment is it?' },
      label: { es: 'Prenda', en: 'Garment' },
      chips: [
        { es: 'Pantalón', en: 'Pants' },
        { es: 'Vestido o falda', en: 'Dress or skirt' },
        { es: 'Saco o traje', en: 'Blazer or suit' },
        { es: 'Hogar (cortinas, manteles)', en: 'Home (curtains, linens)' },
      ] },
  ],

  // ── Move & Transport ──────────────────────────────────────────────────────
  'moving': [
    { key: 'size', type: 'chips',
      q: { es: '¿Qué tan grande es la mudanza?', en: 'How big is the move?' },
      label: { es: 'Tamaño', en: 'Size' },
      chips: [
        { es: 'Pocas cosas', en: 'A few items' },
        { es: 'Estudio o 1 recámara', en: 'Studio or 1BR' },
        { es: '2 recámaras o más', en: '2BR or more' },
      ] },
    { key: 'packing', type: 'chips',
      q: { es: '¿Necesitas ayuda para empacar?', en: 'Do you need packing help?' },
      label: { es: 'Empaque', en: 'Packing' },
      chips: [
        { es: 'Sí, necesito ayuda', en: 'Yes, need help' },
        { es: 'Solo mover', en: 'Just moving' },
      ] },
    { key: 'access', type: 'chips',
      q: { es: '¿Hay escaleras o elevador?', en: 'Any stairs or elevator?' },
      label: { es: 'Acceso', en: 'Access' },
      chips: [
        { es: 'Elevador', en: 'Elevator' },
        { es: 'Escaleras', en: 'Stairs' },
        { es: 'Planta baja', en: 'Ground floor' },
      ] },
  ],
  'large-items': [
    { key: 'item', type: 'chips',
      q: { es: '¿Qué vamos a mover?', en: "What's being moved?" },
      label: { es: 'Objeto', en: 'Item' },
      chips: [
        { es: 'Sofá o sala', en: 'Sofa' },
        { es: 'Colchón', en: 'Mattress' },
        { es: 'Electrodoméstico', en: 'Appliance' },
        { es: 'Comedor', en: 'Dining table' },
        { es: 'Otro', en: 'Other' },
      ] },
    { key: 'access', type: 'chips',
      q: { es: '¿Hay escaleras o elevador?', en: 'Any stairs or elevator?' },
      label: { es: 'Acceso', en: 'Access' },
      chips: [
        { es: 'Elevador', en: 'Elevator' },
        { es: 'Escaleras', en: 'Stairs' },
        { es: 'Planta baja', en: 'Ground floor' },
      ] },
  ],
  'errands': [
    { key: 'errand', type: 'chips',
      q: { es: '¿Qué tipo de mandado es?', en: "What's the errand?" },
      label: { es: 'Mandado', en: 'Errand' },
      chips: [
        { es: 'Súper', en: 'Groceries' },
        { es: 'Farmacia', en: 'Pharmacy' },
        { es: 'Recoger o entregar', en: 'Pickup or drop-off' },
        { es: 'Devolución', en: 'Return' },
      ] },
    { key: 'what', type: 'text',
      q: { es: '¿Qué necesitas que hagamos o compremos?', en: 'What do you need us to do or buy?' },
      label: { es: 'Detalle', en: 'Details' },
      chips: [] },
  ],
  'deliveries': [
    { key: 'item', type: 'chips',
      q: { es: '¿Qué vamos a entregar?', en: 'What are we delivering?' },
      label: { es: 'Entrega', en: 'Delivery' },
      chips: [
        { es: 'Paquete', en: 'Package' },
        { es: 'Comida o catering', en: 'Food or catering' },
        { es: 'Flores o regalo', en: 'Flowers or gift' },
        { es: 'Compra de tienda', en: 'Store purchase' },
      ] },
    { key: 'when', type: 'chips',
      q: { es: '¿Para cuándo la necesitas?', en: 'When do you need it?' },
      label: { es: 'Cuándo', en: 'When' },
      chips: [
        { es: 'Hoy mismo', en: 'Same day' },
        { es: 'Programada', en: 'Scheduled' },
        { es: 'Recurrente', en: 'Recurring' },
      ] },
  ],

  // ── Wellness & Personal Care ──────────────────────────────────────────────
  'massage': [
    { key: 'type', type: 'chips',
      q: { es: '¿Qué tipo de masaje buscas?', en: 'What type of massage?' },
      label: { es: 'Tipo', en: 'Type' },
      chips: [
        { es: 'Relajante', en: 'Relaxation' },
        { es: 'Descontracturante', en: 'Deep tension' },
        { es: 'Recuperación muscular', en: 'Muscle recovery' },
      ] },
    { key: 'people', type: 'chips',
      q: { es: '¿Para cuántas personas?', en: 'For how many people?' },
      label: { es: 'Personas', en: 'People' },
      chips: [
        { es: 'Solo yo', en: 'Just me' },
        { es: 'Dos', en: 'Two' },
      ] },
  ],
  'therapist': [
    { key: 'support', type: 'chips',
      q: { es: '¿Qué tipo de acompañamiento buscas?', en: 'What kind of support?' },
      label: { es: 'Apoyo', en: 'Support' },
      chips: [
        { es: 'Individual', en: 'Individual' },
        { es: 'Pareja', en: 'Couples' },
        { es: 'Adolescente', en: 'Teen' },
      ] },
    { key: 'focus', type: 'chips',
      q: { es: '¿Sobre qué quieres trabajar?', en: 'What would you like to focus on?' },
      label: { es: 'Tema', en: 'Focus' },
      chips: [
        { es: 'Ansiedad o estrés', en: 'Anxiety or stress' },
        { es: 'Duelo o cambio', en: 'Grief or transition' },
        { es: 'Solo explorar', en: 'Just exploring' },
      ] },
  ],
  'personal-trainer': [
    { key: 'goal', type: 'chips',
      q: { es: '¿Cuál es tu meta?', en: "What's your goal?" },
      label: { es: 'Meta', en: 'Goal' },
      chips: [
        { es: 'Fuerza', en: 'Strength' },
        { es: 'Bajar de peso', en: 'Weight loss' },
        { es: 'Movilidad', en: 'Mobility' },
        { es: 'Empezar', en: 'Get started' },
      ] },
    { key: 'level', type: 'chips',
      q: { es: '¿Cuál es tu nivel?', en: "What's your level?" },
      label: { es: 'Nivel', en: 'Level' },
      chips: [
        { es: 'Principiante', en: 'Beginner' },
        { es: 'Intermedio', en: 'Intermediate' },
        { es: 'Avanzado', en: 'Advanced' },
      ] },
  ],
  'pet-care': [
    { key: 'need', type: 'chips',
      q: { es: '¿Qué necesita tu mascota?', en: 'What does your pet need?' },
      label: { es: 'Servicio', en: 'Service' },
      chips: [
        { es: 'Paseo', en: 'Walking' },
        { es: 'Cuidado', en: 'Sitting' },
        { es: 'Baño y aseo', en: 'Bath & grooming' },
        { es: 'Visita de alimento', en: 'Feeding visit' },
      ] },
    { key: 'pet', type: 'chips',
      q: { es: '¿Qué tipo de mascota es?', en: 'What kind of pet?' },
      label: { es: 'Mascota', en: 'Pet' },
      chips: [
        { es: 'Perro', en: 'Dog' },
        { es: 'Gato', en: 'Cat' },
        { es: 'Otra', en: 'Other' },
      ] },
  ],
  'child-care': [
    { key: 'when', type: 'chips',
      q: { es: '¿Cuándo necesitas el cuidado?', en: 'When do you need care?' },
      label: { es: 'Cuándo', en: 'When' },
      chips: [
        { es: 'Después de escuela', en: 'After school' },
        { es: 'Por la noche', en: 'Evening' },
        { es: 'Fin de semana', en: 'Weekend' },
        { es: 'Por horas', en: 'By the hour' },
      ] },
    { key: 'age', type: 'chips',
      q: { es: '¿Qué edad tienen los niños?', en: 'How old are the kids?' },
      label: { es: 'Edad', en: 'Age' },
      chips: [
        { es: 'Bebé', en: 'Infant' },
        { es: 'Pequeño', en: 'Toddler' },
        { es: 'En edad escolar', en: 'School-age' },
      ] },
  ],
  'elder-assistance': [
    { key: 'help', type: 'chips',
      q: { es: '¿Qué tipo de ayuda necesitas?', en: 'What kind of help?' },
      label: { es: 'Ayuda', en: 'Help' },
      chips: [
        { es: 'Compañía', en: 'Companionship' },
        { es: 'Medicamentos', en: 'Medication' },
        { es: 'Citas médicas', en: 'Appointments' },
        { es: 'Tareas diarias', en: 'Daily tasks' },
      ] },
    { key: 'when', type: 'chips',
      q: { es: '¿Cada cuándo lo necesitas?', en: 'How often do you need it?' },
      label: { es: 'Cuándo', en: 'When' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Por horas', en: 'Hourly' },
        { es: 'Recurrente', en: 'Recurring' },
      ] },
  ],

  // ── Suppliers ─────────────────────────────────────────────────────────────
  'artisan-bread': [
    { key: 'type', type: 'chips',
      q: { es: '¿Qué tipo de pan buscas?', en: 'What kind of bread?' },
      label: { es: 'Producto', en: 'Product' },
      chips: [
        { es: 'Masa madre', en: 'Sourdough' },
        { es: 'Pan dulce', en: 'Sweet bread' },
        { es: 'Para desayuno', en: 'Breakfast' },
        { es: 'Bollos', en: 'Rolls' },
      ] },
    { key: 'when', type: 'chips',
      q: { es: '¿Es un pedido único o recurrente?', en: 'One-time or recurring order?' },
      label: { es: 'Pedido', en: 'Order' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Suscripción semanal', en: 'Weekly subscription' },
      ] },
  ],
  'fresh-dairy': [
    { key: 'product', type: 'chips',
      q: { es: '¿Qué productos necesitas?', en: 'What products do you need?' },
      label: { es: 'Producto', en: 'Product' },
      chips: [
        { es: 'Leche y yogurt', en: 'Milk & yogurt' },
        { es: 'Quesos', en: 'Cheese' },
        { es: 'Mantequilla y crema', en: 'Butter & cream' },
        { es: 'Sin lactosa', en: 'Lactose-free' },
      ] },
    { key: 'when', type: 'chips',
      q: { es: '¿Es un pedido único o recurrente?', en: 'One-time or recurring order?' },
      label: { es: 'Pedido', en: 'Order' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Recurrente', en: 'Recurring' },
      ] },
  ],
  'pharmacy': [
    { key: 'need', type: 'chips',
      q: { es: '¿Qué necesitas?', en: 'What do you need?' },
      label: { es: 'Necesito', en: 'Need' },
      chips: [
        { es: 'Receta', en: 'Prescription' },
        { es: 'Sin receta', en: 'Over-the-counter' },
        { es: 'Botiquín', en: 'First-aid' },
        { es: 'Bebé', en: 'Baby care' },
      ] },
    { key: 'urgency', type: 'chips',
      q: { es: '¿Para cuándo lo necesitas?', en: 'When do you need it?' },
      label: { es: 'Urgencia', en: 'Urgency' },
      chips: [
        { es: 'Hoy mismo', en: 'Same day' },
        { es: 'Sin prisa', en: 'No rush' },
      ] },
  ],
  'catering': [
    { key: 'occasion', type: 'chips',
      q: { es: '¿Cuál es la ocasión?', en: "What's the occasion?" },
      label: { es: 'Ocasión', en: 'Occasion' },
      chips: [
        { es: 'Oficina', en: 'Office' },
        { es: 'Fiesta', en: 'Party' },
        { es: 'Reunión pequeña', en: 'Small gathering' },
      ] },
    { key: 'guests', type: 'chips',
      q: { es: '¿Para cuántas personas?', en: 'For how many people?' },
      label: { es: 'Personas', en: 'Guests' },
      chips: [
        { es: 'Menos de 10', en: 'Under 10' },
        { es: '10-25', en: '10-25' },
        { es: 'Más de 25', en: 'More than 25' },
      ] },
  ],
  'organic-butcher': [
    { key: 'product', type: 'chips',
      q: { es: '¿Qué tipo de corte buscas?', en: 'What kind of cuts?' },
      label: { es: 'Producto', en: 'Product' },
      chips: [
        { es: 'Cortes para asar', en: 'Grill cuts' },
        { es: 'Pollo', en: 'Chicken' },
        { es: 'Carne molida', en: 'Ground meat' },
        { es: 'Especiales', en: 'Specialty cuts' },
      ] },
    { key: 'amount', type: 'chips',
      q: { es: '¿Qué cantidad necesitas?', en: 'How much do you need?' },
      label: { es: 'Cantidad', en: 'Amount' },
      chips: [
        { es: 'Para una comida', en: 'For one meal' },
        { es: 'Para la semana', en: 'For the week' },
        { es: 'Surtido grande', en: 'Large order' },
      ] },
  ],
  'fish': [
    { key: 'product', type: 'chips',
      q: { es: '¿Qué buscas?', en: 'What are you looking for?' },
      label: { es: 'Producto', en: 'Product' },
      chips: [
        { es: 'Salmón', en: 'Salmon' },
        { es: 'Camarón', en: 'Shrimp' },
        { es: 'Atún', en: 'Tuna' },
        { es: 'Mariscos surtidos', en: 'Mixed seafood' },
        { es: 'Pescado entero', en: 'Whole fish' },
      ] },
    { key: 'amount', type: 'chips',
      q: { es: '¿Qué cantidad necesitas?', en: 'How much do you need?' },
      label: { es: 'Cantidad', en: 'Amount' },
      chips: [
        { es: 'Para una comida', en: 'For one meal' },
        { es: 'Para la semana', en: 'For the week' },
        { es: 'Para familia', en: 'Family pack' },
      ] },
  ],
  'organic-vegetables': [
    { key: 'product', type: 'chips',
      q: { es: '¿Qué buscas?', en: 'What are you looking for?' },
      label: { es: 'Producto', en: 'Product' },
      chips: [
        { es: 'Caja surtida', en: 'Mixed box' },
        { es: 'Hojas y ensalada', en: 'Leafy greens' },
        { es: 'Para cocinar', en: 'For cooking' },
        { es: 'Para jugos', en: 'For juicing' },
      ] },
    { key: 'when', type: 'chips',
      q: { es: '¿Es un pedido único o recurrente?', en: 'One-time or recurring order?' },
      label: { es: 'Pedido', en: 'Order' },
      chips: [
        { es: 'Una vez', en: 'One time' },
        { es: 'Caja semanal', en: 'Weekly box' },
      ] },
  ],
};
